Update tabs to new UI
celo-org/blockscout pull request #620
Opened 2022-04-18 11:12 UTC by eruizgar91

### Description

Update tabs structure to new UI.
 
 ### Other changes

No

### Issues

 - Fixes #454

### Checklist

  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I added code comments for anything non trivial.
  - [ ] I added documentation for my changes.
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/celo-org/monorepo to update the list and default values of env vars.
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools.

2022-04-20 11:02 UTC, carterqw2 requested changes

2022-04-20 12:39 UTC, eruizgar91 commented on apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
> +                    gettext("Validated Txt"),
Yes, it makes more sense. Or even Txns as in Etherscan. What do you think @mattdkim ?

2022-04-20 16:16 UTC, mattdkim commented on apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
> +                      gettext("Celo Tokens"),
Makes sense, I was mistaken that Celo tab renders all Celo contracts. It'd make sense to rename the tab to "Top Celo Holders" or "Top Accounts"

2022-04-22 12:02 UTC, carterqw2 approved these changes
Looks good to me!

2022-04-22 12:04 UTC, merged