Obasilakis/add election rewards fetcher
celo-org/blockscout pull request #644
Opened 2022-05-20 16:48 UTC by obasilakis

_[GitHub keywords to close any associated issues](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)_

### Description

Code to index election rewards, meaning voter, validator and group rewards. One thing to notice in the election rewards fetcher is that the functions responsible for getting voter rewards and validator+group rewards will return the argument if the rewards already exist in the argument (thus avoiding calls to the archive node and to the db). If there is a changeset error, the rewards of that type are removed from the map so that the functions mentioned above try to get them again.
 
 ### Other changes

Instead of using block hash in celo pending epoch operations, we now use block numbers.

### Checklist

  - [X] If I added new functionality, I added tests covering it.
  - [X] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [X] I added code comments for anything non trivial.
  - [ ] I added documentation for my changes.
  - [X] If I added/changed/removed ENV var, I submitted a PR to https://github.com/celo-org/monorepo to update the list and default values of env vars.
  - [X] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools.

2022-05-23 15:51 UTC, carterqw2 commented on apps/explorer/lib/explorer/celo/voter_rewards.ex
> +    query =
I think it's worth documenting what this function does and why.

2022-05-31 10:52 UTC, carterqw2 commented on apps/indexer/lib/indexer/fetcher/celo_election_rewards.ex
> +      timeout: :infinity
Are we sure about this?

2022-05-31 10:58 UTC, carterqw2 requested changes

2022-05-31 10:58 UTC, carterqw2 commented on apps/indexer/test/indexer/fetcher/celo_election_rewards_test.exs
> +  describe "get_voter_rewards, when voter rewards are passed" do
Would be great to actually test the `get_voter_rewards` method as it looks like you deleted `celo_voter_votes_test`.

2022-05-31 12:10 UTC, rkachowski commented on apps/indexer/lib/indexer/fetcher/celo_election_rewards.ex
> +  defp log_changeset_error(changeset) when not changeset.valid? do
we can move this into the if statement above and just log before returning the error tuple

2022-05-31 13:55 UTC, carterqw2 commented on apps/indexer/test/indexer/fetcher/celo_election_rewards_test.exs
> +  describe "get_voter_rewards, when voter rewards are passed" do
True but that test doesn't check any values except for the reward type. I thought you had some tests that check reward values in the previous version somewhere.

2022-05-31 14:26 UTC, obasilakis commented on apps/explorer/lib/explorer/chain/import/runner/celo_election_rewards.ex
> +          amount: fragment("EXCLUDED.amount"),
Same as with the infinity timeout in the fetcher, I got inspired by the other runners. should we `DO NOTHING` instead?

2022-05-31 14:35 UTC, carterqw2 commented on apps/explorer/lib/explorer/chain/import/runner/celo_election_rewards.ex
> +          amount: fragment("EXCLUDED.amount"),
Looking again, I think the purpose of it is to allow reindexing if we ever need to do that again.

2022-05-31 14:38 UTC, carterqw2 commented on apps/explorer/lib/explorer/chain/import/runner/celo_election_rewards.ex
> +          amount: fragment("EXCLUDED.amount"),
Realistically, it's the only field that can be changed in case of reindexing except for the timestamps, so it's fine.

2022-05-31 15:54 UTC, carterqw2 approved these changes

2022-05-31 15:54 UTC, merged